apiVersion: v1 
kind: Pod
metadata:
  name: nginx
  labels:
   project: roboshop
   purpose: env-demo
spec:
  containers:
  - name: nginx
    image: nginx
  env:
  - name: COURSE
    value: "KUBERENETS"
  - name: TRAINER
    value: "Dinesh Naidu"